### ISSUE TITLE
关于皮肤的修改

### ISSUE THREAD

**Issue by villainousx** [MoLeft/yanglegeyang#5]
https://cat-match-static.easygame2021.com/catMatch/sheep_wx_1_2_0/remote/resources/import/90/9020bbe7-5f82-4103-8834-0e5480b8745c.72bbe.json

批量修改这个json里的【unblock:"false"】为【unblock:true】
不太懂python的json怎么批量修改，可以指导一下吗

**Comment by MoLeft** [comment]
我抓包到的解锁皮肤的接口是https://cat-match.easygame2021.com/sheep/v1/game/update_user_skin?skin=皮肤id

**Comment by villainousx** [comment]
> 我抓包到的解锁皮肤的接口是[https://cat-match.easygame2021.com/sheep/v1/game/update_user_skin?skin=皮肤id](https://cat-match.easygame2021.com/sheep/v1/game/update_user_skin?skin=%E7%9A%AE%E8%82%A4id)

皮肤是存在本地的，这个接口应该是没用的，我发的是本地的，只要修改了false就能本地解锁，但是得批量
